---
- hosts: localhost
  tasks:

    - name: unarchive oracle tar
      unarchive:
        src: download_dir/sql.tar.gz
        dest: download_dir
        mode: 0755

    - name: check if testuser.sql exist
      stat: path=download_dir/testuser.sql
      register: sql_create_user_script

    - name: check if grantuser.sql exist
      stat: path=download_dir/grantuser.sql
      register: sql_grantuser_script

    - name: Get Object_details
      shell: echo exit |sqlplus "{{ oracle_username }}/{{ oracle_pwd }}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host={{ oracle_hostname }})(Port={{ oracle_port }}))(CONNECT_DATA=(SERVICE_NAME= {{ service_name }})))"@download_dir/testuser.sql;
      #environment:
       #  ORACLE_HOME: <<Oracle Home path >>
        # PATH: << bin path >>
         #LD_LIBRARY_PATH: << lib path >>
      when: sql_create_user_script.stat.exists == true


    - name: Get Object_details
      shell: echo exit |sqlplus "{{ oracle_username }}/{{ oracle_pwd }}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host={{ Rds_Endpoint }})(Port={{ oracle_port }}))(CONNECT_DATA=(SERVICE_NAME= {{ service_name }})))"@download_dir/grantuser.sql;
      when: sql_grantuser_script.stat.exists == true

